# Generated by Django 5.2.5 on 2025-09-04 18:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_user_email_verified_emailverificationtoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailDeliveryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_type', models.CharField(choices=[('verification', 'Email Verification'), ('password_reset', 'Password Reset'), ('notification', 'Notification'), ('welcome', 'Welcome Email')], help_text='Type of email sent', max_length=20)),
                ('recipient_email', models.EmailField(help_text='Email address where the email was sent', max_length=254)),
                ('subject', models.CharField(help_text='Email subject line', max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent Successfully'), ('failed', 'Failed to Send'), ('delivered', 'Delivered'), ('bounced', 'Bounced'), ('opened', 'Opened'), ('clicked', 'Clicked')], default='pending', help_text='Current delivery status', max_length=20)),
                ('provider', models.CharField(default='sendgrid', help_text='Email service provider used', max_length=50)),
                ('provider_message_id', models.CharField(blank=True, help_text='Provider-specific message ID', max_length=255)),
                ('error_message', models.TextField(blank=True, help_text='Error message if sending failed')),
                ('attempts', models.PositiveIntegerField(default=1, help_text='Number of sending attempts')),
                ('sent_at', models.DateTimeField(blank=True, help_text='When the email was successfully sent', null=True)),
                ('delivered_at', models.DateTimeField(blank=True, help_text='When the email was delivered', null=True)),
                ('opened_at', models.DateTimeField(blank=True, help_text='When the email was first opened', null=True)),
                ('clicked_at', models.DateTimeField(blank=True, help_text='When a link in the email was first clicked', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Email Delivery Log',
                'verbose_name_plural': 'Email Delivery Logs',
                'db_table': 'email_delivery_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user'], name='email_deliv_user_id_8e1445_idx'), models.Index(fields=['email_type'], name='email_deliv_email_t_1a98e5_idx'), models.Index(fields=['status'], name='email_deliv_status_ea9402_idx'), models.Index(fields=['created_at'], name='email_deliv_created_f160d8_idx'), models.Index(fields=['provider_message_id'], name='email_deliv_provide_48867f_idx')],
            },
        ),
    ]
