# Generated by Django 4.2.7 on 2025-08-06 11:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_additional_requirements'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contracts', '0005_delete_contractamendment'),
        ('reviews', '0002_alter_review_unique_together_review_clarity_rating_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('project', 'reviewer', 'review_type')},
        ),
        migrations.AlterField(
            model_name='review',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='projects.project'),
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('contract', 'reviewer', 'review_type'), ('project', 'reviewer', 'review_type')},
        ),
    ]
