# Generated by Django 5.2.5 on 2025-08-13 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_additional_requirements'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_paid',
            field=models.BooleanField(default=False, help_text='Whether the project has been paid for'),
        ),
    ]
