# Generated by Django 5.2.5 on 2025-08-29 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_is_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='selected_providers',
            field=models.JSONField(blank=True, default=list, help_text='List of selected service provider IDs chosen by client'),
        ),
    ]
