# Generated by Django 5.2.5 on 2025-08-29 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_selected_providers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='selected_providers',
        ),
    ]
