# Generated by Django 4.2.28 on 2026-04-09 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_intakelead'),
    ]

    operations = [
        migrations.AddField(
            model_name='intakelead',
            name='lead_source',
            field=models.CharField(blank=True, help_text='e.g. SEO, Social, Referral', max_length=100),
        ),
        migrations.AddField(
            model_name='intakelead',
            name='role_type',
            field=models.CharField(blank=True, help_text='e.g. Client, Pro, Specialist', max_length=50),
        ),
        migrations.AddField(
            model_name='intakelead',
            name='service_type',
            field=models.CharField(blank=True, help_text='Specific trade or service interest', max_length=100),
        ),
    ]
