# Generated by Django 4.2.7 on 2025-08-08 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='authorize_net_auth_code',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='payment',
            name='authorize_net_response_code',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='payment',
            name='authorize_net_transaction_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='authorize_net_customer_profile_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='authorize_net_payment_profile_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='type',
            field=models.CharField(choices=[('card', 'Credit/Debit Card'), ('bank', 'Bank Transfer'), ('paypal', 'PayPal'), ('stripe', 'Stripe'), ('authorize_net', 'Authorize.Net'), ('wallet', 'Wallet Balance')], max_length=20),
        ),
    ]
