# Generated by Django 4.2.7 on 2025-08-09 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_payment_authorize_net_auth_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('project_payment', 'Project Payment'), ('milestone_payment', 'Milestone Payment'), ('escrow_release', 'Escrow Release'), ('subscription', 'Subscription'), ('refund', 'Refund'), ('withdrawal', 'Withdrawal'), ('platform_fee', 'Platform Fee'), ('wallet_topup', 'Wallet Top-up')], default='project_payment', max_length=30),
        ),
    ]
