# Generated by Django 5.2.5 on 2025-08-12 22:57

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_paymentmethod_account_holder_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='withdrawal',
            name='payment_method',
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='ach_trace_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='estimated_arrival',
            field=models.DateTimeField(blank=True, help_text='Estimated arrival date (1-3 business days)', null=True),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='failure_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='net_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='processing_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_legal_name', models.CharField(help_text='Must match bank account', max_length=255)),
                ('bank_name', models.CharField(max_length=255)),
                ('account_number', models.CharField(max_length=50)),
                ('routing_number', models.CharField(help_text='ACH routing number', max_length=20)),
                ('account_type', models.CharField(choices=[('checking', 'Checking'), ('savings', 'Savings'), ('business', 'Business')], default='checking', max_length=20)),
                ('business_name', models.CharField(blank=True, max_length=255)),
                ('business_ein', models.CharField(blank=True, help_text='Employer Identification Number', max_length=20)),
                ('ssn_last4', models.CharField(blank=True, help_text='Last 4 digits of SSN', max_length=4)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('address_line1', models.CharField(max_length=255)),
                ('address_line2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
                ('country', models.CharField(default='US', help_text='ISO country code', max_length=2)),
                ('phone_number', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending Verification'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('is_default', models.BooleanField(default=False)),
                ('kyc_verified', models.BooleanField(default=False)),
                ('kyc_verified_at', models.DateTimeField(blank=True, null=True)),
                ('verification_notes', models.TextField(blank=True)),
                ('stripe_account_id', models.CharField(blank=True, max_length=255)),
                ('authorize_net_profile_id', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bank Account',
                'verbose_name_plural': 'Bank Accounts',
                'db_table': 'bank_accounts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='bank_account',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals', to='payments.bankaccount'),
            preserve_default=False,
        ),
    ]
