# Generated by Django 5.2.5 on 2025-08-14 19:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0005_delete_contractamendment'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='platform_commission_rate',
            field=models.DecimalField(decimal_places=4, default=0.15, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='contract',
            name='project_balance',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Funds allocated from client's wallet to this contract", max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='contractmilestone',
            name='payment_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contractmilestone',
            name='payment_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='contractmilestone',
            name='payment_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contractmilestone',
            name='payment_status',
            field=models.CharField(choices=[('not_requested', 'Not Requested'), ('requested', 'Payment Requested'), ('approved', 'Payment Approved'), ('paid', 'Paid'), ('rejected', 'Payment Rejected')], default='not_requested', max_length=20),
        ),
        migrations.AddField(
            model_name='contractmilestone',
            name='platform_commission_rate',
            field=models.DecimalField(decimal_places=4, default=0.15, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='contractmilestone',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
