# Generated by Django 5.2.5 on 2025-08-16 23:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0006_contract_platform_commission_rate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contract',
            old_name='project_balance',
            new_name='contract_balance',
        ),
        migrations.AddField(
            model_name='contract',
            name='professional_balance',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Funds transferred to professional's pending balance (available after 3 days)", max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='contract',
            name='professional_balance_release_date',
            field=models.DateTimeField(blank=True, help_text='Date when professional balance becomes available (3 days after transfer)', null=True),
        ),
    ]
