# Generated by Django 5.2.5 on 2025-08-17 02:06

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0007_rename_project_balance_contract_contract_balance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractInstallment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('transferred', 'Transferred'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('transferred_at', models.DateTimeField(blank=True, null=True)),
                ('net_amount_to_professional', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('platform_commission_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='contracts.contract')),
            ],
            options={
                'verbose_name': 'Contract Installment',
                'verbose_name_plural': 'Contract Installments',
                'db_table': 'contract_installments',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['contract'], name='contract_in_contrac_8b310d_idx'), models.Index(fields=['status'], name='contract_in_status_3a8603_idx'), models.Index(fields=['created_at'], name='contract_in_created_2369ce_idx')],
            },
        ),
    ]
