# Generated by Django 5.2.5 on 2025-08-17 03:05

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0008_contractinstallment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Gross payment amount requested', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('description', models.TextField(blank=True, help_text='Description of work completed or payment reason')),
                ('platform_commission_rate', models.DecimalField(decimal_places=4, default=0.15, max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('platform_commission_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('net_amount_to_professional', models.DecimalField(decimal_places=2, default=0, help_text='Amount transferred to professional after commission', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('pending', 'Pending Client Approval'), ('approved', 'Approved by Client'), ('transferred', 'Transferred to Professional'), ('completed', 'Completed (Available to Professional)'), ('cancelled', 'Cancelled'), ('disputed', 'Disputed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('transferred_at', models.DateTimeField(blank=True, null=True)),
                ('available_at', models.DateTimeField(blank=True, help_text='When funds become available to professional (3 days after transfer)', null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('client_notes', models.TextField(blank=True, help_text='Notes from client when approving/rejecting')),
                ('approved_by', models.ForeignKey(blank=True, help_text='Client who approved the payment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_payments', to=settings.AUTH_USER_MODEL)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_payments', to='contracts.contract')),
                ('requested_by', models.ForeignKey(help_text='Professional who requested the payment', on_delete=django.db.models.deletion.CASCADE, related_name='requested_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contract Payment',
                'verbose_name_plural': 'Contract Payments',
                'db_table': 'contract_payments',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['contract'], name='contract_pa_contrac_f0e03a_idx'), models.Index(fields=['status'], name='contract_pa_status_734978_idx'), models.Index(fields=['created_at'], name='contract_pa_created_3211f0_idx'), models.Index(fields=['available_at'], name='contract_pa_availab_bbb724_idx')],
            },
        ),
    ]
